minimumReleaseAgeExcludePrune: true
minimumReleaseAgeExclude:
  - '@modelcontextprotocol/core@2.2.0'
  - '@modelcontextprotocol/server@2.2.0'

trustPolicy: no-downgrade
shellEmulator: true

allowBuilds:
  core-js-pure: true
  esbuild: true
  sharp: true
  simple-git-hooks: true
  workerd: true

onlyBuiltDependencies:
  - core-js-pure
  - esbuild
  - sharp
  - simple-git-hooks
  - workerd
